//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://tempuri.org/")]
    public partial class Clientes : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string EmailField;
        
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DOB
        {
            get
            {
                return this.DOBField;
            }
            set
            {
                this.DOBField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesWS.ClienteWSSoap")]
    public interface ClienteWSSoap
    {
        
        // CODEGEN: Generating message contract since element name NomeClienteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NomeCliente", ReplyAction="*")]
        ClientesWS.NomeClienteResponse NomeCliente(ClientesWS.NomeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NomeCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientesWS.NomeClienteResponse> NomeClienteAsync(ClientesWS.NomeClienteRequest request);
        
        // CODEGEN: Generating message contract since element name ListaDeClientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDeClientes", ReplyAction="*")]
        ClientesWS.ListaDeClientesResponse ListaDeClientes(ClientesWS.ListaDeClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDeClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientesWS.ListaDeClientesResponse> ListaDeClientesAsync(ClientesWS.ListaDeClientesRequest request);
        
        // CODEGEN: Generating message contract since element name ocliente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvarCliente", ReplyAction="*")]
        ClientesWS.SalvarClienteResponse SalvarCliente(ClientesWS.SalvarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientesWS.SalvarClienteResponse> SalvarClienteAsync(ClientesWS.SalvarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NomeClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NomeCliente", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.NomeClienteRequestBody Body;
        
        public NomeClienteRequest()
        {
        }
        
        public NomeClienteRequest(ClientesWS.NomeClienteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NomeClienteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        public NomeClienteRequestBody()
        {
        }
        
        public NomeClienteRequestBody(int idCliente)
        {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NomeClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NomeClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.NomeClienteResponseBody Body;
        
        public NomeClienteResponse()
        {
        }
        
        public NomeClienteResponse(ClientesWS.NomeClienteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NomeClienteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomeClienteResult;
        
        public NomeClienteResponseBody()
        {
        }
        
        public NomeClienteResponseBody(string NomeClienteResult)
        {
            this.NomeClienteResult = NomeClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDeClientesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDeClientes", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.ListaDeClientesRequestBody Body;
        
        public ListaDeClientesRequest()
        {
        }
        
        public ListaDeClientesRequest(ClientesWS.ListaDeClientesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaDeClientesRequestBody
    {
        
        public ListaDeClientesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDeClientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDeClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.ListaDeClientesResponseBody Body;
        
        public ListaDeClientesResponse()
        {
        }
        
        public ListaDeClientesResponse(ClientesWS.ListaDeClientesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDeClientesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientesWS.Clientes[] ListaDeClientesResult;
        
        public ListaDeClientesResponseBody()
        {
        }
        
        public ListaDeClientesResponseBody(ClientesWS.Clientes[] ListaDeClientesResult)
        {
            this.ListaDeClientesResult = ListaDeClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarCliente", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.SalvarClienteRequestBody Body;
        
        public SalvarClienteRequest()
        {
        }
        
        public SalvarClienteRequest(ClientesWS.SalvarClienteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarClienteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientesWS.Clientes ocliente;
        
        public SalvarClienteRequestBody()
        {
        }
        
        public SalvarClienteRequestBody(ClientesWS.Clientes ocliente)
        {
            this.ocliente = ocliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientesWS.SalvarClienteResponseBody Body;
        
        public SalvarClienteResponse()
        {
        }
        
        public SalvarClienteResponse(ClientesWS.SalvarClienteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarClienteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SalvarClienteResult;
        
        public SalvarClienteResponseBody()
        {
        }
        
        public SalvarClienteResponseBody(bool SalvarClienteResult)
        {
            this.SalvarClienteResult = SalvarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface ClienteWSSoapChannel : ClientesWS.ClienteWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class ClienteWSSoapClient : System.ServiceModel.ClientBase<ClientesWS.ClienteWSSoap>, ClientesWS.ClienteWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClienteWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ClienteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), ClienteWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClienteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClienteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientesWS.NomeClienteResponse ClientesWS.ClienteWSSoap.NomeCliente(ClientesWS.NomeClienteRequest request)
        {
            return base.Channel.NomeCliente(request);
        }
        
        public string NomeCliente(int idCliente)
        {
            ClientesWS.NomeClienteRequest inValue = new ClientesWS.NomeClienteRequest();
            inValue.Body = new ClientesWS.NomeClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            ClientesWS.NomeClienteResponse retVal = ((ClientesWS.ClienteWSSoap)(this)).NomeCliente(inValue);
            return retVal.Body.NomeClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientesWS.NomeClienteResponse> ClientesWS.ClienteWSSoap.NomeClienteAsync(ClientesWS.NomeClienteRequest request)
        {
            return base.Channel.NomeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientesWS.NomeClienteResponse> NomeClienteAsync(int idCliente)
        {
            ClientesWS.NomeClienteRequest inValue = new ClientesWS.NomeClienteRequest();
            inValue.Body = new ClientesWS.NomeClienteRequestBody();
            inValue.Body.idCliente = idCliente;
            return ((ClientesWS.ClienteWSSoap)(this)).NomeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientesWS.ListaDeClientesResponse ClientesWS.ClienteWSSoap.ListaDeClientes(ClientesWS.ListaDeClientesRequest request)
        {
            return base.Channel.ListaDeClientes(request);
        }
        
        public ClientesWS.Clientes[] ListaDeClientes()
        {
            ClientesWS.ListaDeClientesRequest inValue = new ClientesWS.ListaDeClientesRequest();
            inValue.Body = new ClientesWS.ListaDeClientesRequestBody();
            ClientesWS.ListaDeClientesResponse retVal = ((ClientesWS.ClienteWSSoap)(this)).ListaDeClientes(inValue);
            return retVal.Body.ListaDeClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientesWS.ListaDeClientesResponse> ClientesWS.ClienteWSSoap.ListaDeClientesAsync(ClientesWS.ListaDeClientesRequest request)
        {
            return base.Channel.ListaDeClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientesWS.ListaDeClientesResponse> ListaDeClientesAsync()
        {
            ClientesWS.ListaDeClientesRequest inValue = new ClientesWS.ListaDeClientesRequest();
            inValue.Body = new ClientesWS.ListaDeClientesRequestBody();
            return ((ClientesWS.ClienteWSSoap)(this)).ListaDeClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientesWS.SalvarClienteResponse ClientesWS.ClienteWSSoap.SalvarCliente(ClientesWS.SalvarClienteRequest request)
        {
            return base.Channel.SalvarCliente(request);
        }
        
        public bool SalvarCliente(ClientesWS.Clientes ocliente)
        {
            ClientesWS.SalvarClienteRequest inValue = new ClientesWS.SalvarClienteRequest();
            inValue.Body = new ClientesWS.SalvarClienteRequestBody();
            inValue.Body.ocliente = ocliente;
            ClientesWS.SalvarClienteResponse retVal = ((ClientesWS.ClienteWSSoap)(this)).SalvarCliente(inValue);
            return retVal.Body.SalvarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientesWS.SalvarClienteResponse> ClientesWS.ClienteWSSoap.SalvarClienteAsync(ClientesWS.SalvarClienteRequest request)
        {
            return base.Channel.SalvarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientesWS.SalvarClienteResponse> SalvarClienteAsync(ClientesWS.Clientes ocliente)
        {
            ClientesWS.SalvarClienteRequest inValue = new ClientesWS.SalvarClienteRequest();
            inValue.Body = new ClientesWS.SalvarClienteRequestBody();
            inValue.Body.ocliente = ocliente;
            return ((ClientesWS.ClienteWSSoap)(this)).SalvarClienteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClienteWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ClienteWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClienteWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44343/ClienteWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ClienteWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44343/ClienteWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ClienteWSSoap,
            
            ClienteWSSoap12,
        }
    }
}
